# Generated by Django 5.2.7 on 2025-11-03 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distraction_name', models.CharField()),
                ('distraction_icon', models.ImageField(upload_to='main_app/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField()),
                ('tag_color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ToDoList Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField()),
                ('is_done', models.CharField(choices=[(False, 'Not Done'), (True, 'Done')], default=False)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main_app.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='FocusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DurationField(blank=True, null=True, verbose_name='Started At:')),
                ('end_time', models.DurationField(blank=True, null=True, verbose_name='Ended At:')),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('focus_level', models.CharField(blank=True, choices=[(1, 'Distracted'), (2, 'Unfocused'), (3, 'Average'), (4, 'Focused'), (5, 'Flow State')], max_length=1, null=True)),
                ('outcomes', models.TextField(blank=True)),
                ('distraction', models.ManyToManyField(to='main_app.distraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.tag')),
                ('todolist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist')),
            ],
        ),
    ]
