# Generated by Django 5.2.7 on 2025-10-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ToDoList Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField()),
                ('is_done', models.CharField(choices=[('N', 'Not Done'), ('Y', 'Done')], default='N', max_length=1)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist')),
            ],
        ),
    ]
