# Generated by Django 5.2.7 on 2025-10-28 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distraction_name', models.CharField()),
                ('distraction_icon', models.ImageField(upload_to='main_app/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField()),
                ('tag_color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='ToDoList Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='FocusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Started At:')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Ended At:')),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'Paused'), ('E', 'Ended')], default='S', max_length=1)),
                ('focus_level', models.CharField(choices=[(1, 'Distracted'), (2, 'Unfocused'), (3, 'Average'), (4, 'Focused'), (5, 'Flow State')], default=3, max_length=1)),
                ('outcomes', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='FocusLog Session Creation Date')),
                ('distraction', models.ManyToManyField(to='main_app.distraction')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField()),
                ('is_done', models.CharField(choices=[('N', 'Not Done'), ('Y', 'Done')], default='N', max_length=1)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist')),
            ],
        ),
    ]
