# Generated by Django 5.2.7 on 2025-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuslog',
            name='distraction',
            field=models.ManyToManyField(blank=True, to='main_app.distraction'),
        ),
        migrations.AlterField(
            model_name='focuslog',
            name='focus_level',
            field=models.CharField(choices=[(1, 'Distracted'), (2, 'Unfocused'), (3, 'Average'), (4, 'Focused'), (5, 'Flow State')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='focuslog',
            name='outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='focuslog',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('P', 'Paused'), ('E', 'Ended')], max_length=1, null=True),
        ),
    ]
