# Generated by Django 5.2.7 on 2025-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_focuslog_distraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuslog',
            name='distraction',
            field=models.ManyToManyField(to='main_app.distraction'),
        ),
        migrations.AlterField(
            model_name='focuslog',
            name='focus_level',
            field=models.CharField(choices=[('1', 'Distracted'), ('2', 'Unfocused'), ('3', 'Average'), ('4', 'Focused'), ('5', 'Flow State')], max_length=1, null=True),
        ),
    ]
